### ISSUE TITLE
java.lang.VerifyError: class org.openstreetmap.josm.plugins.continuosDownload.DownloadOsmTask2 overrides final method rememberErrorMessage

### ISSUE THREAD

**Issue by matkoniecz** [Gnonthgol/JOSM-continuos-download#16]
In r8926 loading plugin fails with

```
INFO: loading plugin 'continuosDownload' (version 1413902943)
ERROR: org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin continuosDownload. Cause: java.lang.reflect.InvocationTargetException. Cause: java.lang.VerifyError: class org.openstreetmap.josm.plugins.continuosDownload.DownloadOsmTask2 overrides final method rememberErrorMessage.(Ljava/lang/String;)V
org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin continuosDownload
    at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:336)
    at org.openstreetmap.josm.plugins.PluginHandler.loadPlugin(PluginHandler.java:698)
    at org.openstreetmap.josm.plugins.PluginHandler.loadPlugins(PluginHandler.java:758)
    at org.openstreetmap.josm.plugins.PluginHandler.loadLatePlugins(PluginHandler.java:797)
    at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:463)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:333)
    ... 4 more
Caused by: java.lang.VerifyError: class org.openstreetmap.josm.plugins.continuosDownload.DownloadOsmTask2 overrides final method rememberErrorMessage.(Ljava/lang/String;)V
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.openstreetmap.josm.plugins.continuosDownload.DownloadPlugin.<init>(DownloadPlugin.java:54)
```

**Comment by matkoniecz** [comment]
see also https://josm.openstreetmap.de/ticket/11998#ticket - I have no idea is it JOSM bug or a plugin bug.

**Comment by don-vip** [comment]
This method is now final but I have added two protected booleans in JOSM 8927 to simplify what you need to do.

**Comment by don-vip** [comment]
Issue closed in https://github.com/JOSM/JOSM-continuos-download/releases/tag/v1.2
